#!/bin/sh

# ===========================================================================
# Orange: 0.1.0
#
# Copyright (c) 2017 Luke Smith <lsmith@zenoscave.com>
#
# Please refer to LICENSE for copyright information
#
#      File    : clean
#      Purpose : Orange cleanup utility script
# ===========================================================================

(cd .. && mkdir -p dists && if [ -e orange-*.iso ]; then mv orange-*.iso dists; fi)
